version: "3.2"
services:

  nest:
    build:
      context: .
      dockerfile: "Dockerfile"
    container_name: nestjs
    restart: unless-stopped
    tty: true
    depends_on: 
      - mongo
    ports:
      - "3000:3000"
    networks:
      - nestjs_network

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    tty: true
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: project
    networks:
      - nestjs_network

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    tty: true
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - nestjs_network

  redis:
    image: redis:6.2-alpine
    container_name: redis-service
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    networks:
      - nestjs_network

volumes:
  mongo_data:
    driver: local
  cache:
    driver: local

networks:
  nestjs_network:
